Finish the task
utn-integrador-III/lab-management-api pull request #19
Opened 2024-07-26 08:19 UTC by Joxini

Hola buenas noches, en este pull-request, añadí ciertas cosas que vi que hacían falta, como lo es el get-all en Issue y en el .env.example, añadí unos atributos que faltaban para usar la autenticación, aqui les dejo las pruebas de que todo esta funcional.
JIRA: https://ever-utn.atlassian.net/jira/core/projects/US/board?selectedIssue=US-120
### **Get-All:**
![image](https://github.com/user-attachments/assets/23c2b9f1-84ad-4f19-825a-5cc22e0c59b6)
![image](https://github.com/user-attachments/assets/7b1ad3d1-ac57-4692-83cf-2a71dd7177b6)
![image](https://github.com/user-attachments/assets/c9caa07a-3edf-441f-850d-6f69f1be33f4)

### **Delete:**

### **Not Autentication:**
![image](https://github.com/user-attachments/assets/f3213ba1-8592-4826-a9fc-15618828032e)

### **status = "WIP":**
![image](https://github.com/user-attachments/assets/3fc8538d-c304-48e1-9d4d-ea2460af7d18)

### **status = "Pending":**
![image](https://github.com/user-attachments/assets/d00eee4d-cdd6-40cc-b828-3d6b5981c360)
![image](https://github.com/user-attachments/assets/ce09f3fb-05e4-4e62-b10f-ca0c52ceb378)

2024-07-26 16:19 UTC, ebarahonautn requested changes

2024-07-26 16:19 UTC, ebarahonautn commented on controllers/issue/controller.py
@Joxini in the POST method, this validations is not required because a lab can have some issue reports.

```
Issue_exists = IssueModel.get_by_name(data.get("lab"))
if Issue_exists:
    return ServerResponse(message='Issue already exists', 
                          message_code=LAB_ALREADY_EXIST, status=StatusCode.CONFLICT)
```
 
Also, POST method needs to receive only this values in the body:
```
{
  "lab": "Lab A",
  "person": {
    "email": "student@example.com",
    "student_name": "John Doe"
  },
  "issue": [
    {
      "computer": "Computer 1",
      "description": "The computer is not turning on.",
    }
  ],
  "observations": "No additional observations."
}
```


**But you need to insert:**
```
{
  "lab": "Lab A",
  "person": {
    "email": "student@example.com",
    "student_name": "John Doe"
  },
  "issue": [
    {
      "computer": "Computer 1",
      "description": "The computer is not turning on.",
      "is_repaired": false --> default value is false
    }
  ],
  "report_to": "", --> default value is empty
  "observations": "No additional observations.",
  "status": "Pending", --> default value is Pending
  "update": [] --> default value is an empty array
}
```

2024-07-26 16:19 UTC, ebarahonautn commented on swagger.yml
@Joxini please update the values in the body and the response with code 201

```
{
  "lab": "Lab A",
  "person": {
    "email": "student@example.com",
    "student_name": "John Doe"
  },
  "issue": [
    {
      "computer": "Computer 1",
      "description": "The computer is not turning on.",
    }
  ],
  "observations": "No additional observations."
}
```

and the response code 201
```
{
  "_id": "29ufedq9v8dvud9ff",
  "lab": "Lab A",
  "person": {
    "email": "student@example.com",
    "student_name": "John Doe"
  },
  "issue": [
    {
      "computer": "Computer 1",
      "description": "The computer is not turning on.",
      "is_repaired": false
    }
  ],
  "report_to": "",
  "observations": "No additional observations.",
  "status": "Pending",
  "update": []
}
```

2024-07-27 01:18 UTC, Joxini commented on swagger.yml
Method Post:

![image](https://github.com/user-attachments/assets/5ae273b1-58be-4ee1-8020-7912d9f2dcad)
![image](https://github.com/user-attachments/assets/f517c1f9-98d0-4a2c-a5ce-2a53b49a5fcc)

Method GetAll:
![image](https://github.com/user-attachments/assets/0207668f-709d-42ab-b5d1-82a189199503)

Swagger:
Post:
Body=
![image](https://github.com/user-attachments/assets/251335c6-c69d-4e1e-a93c-7c5e8885854a)
Response= 
![image](https://github.com/user-attachments/assets/7b1cf759-6254-43ba-9d08-e46922da3b3c)

GetAll:
![image](https://github.com/user-attachments/assets/f08cadba-6347-4263-8295-fbcecb5bae14)

2024-07-27 02:07 UTC, ebarahonautn approved these changes

2024-07-27 02:08 UTC, merged