SC-82 Create an endpoint to get all professor info
utn-integrador-III/lab-management-api pull request #4
Opened 2024-07-11 16:13 UTC by JOSEEAND

2024-07-12 21:27 UTC, GenVallejo approved these changes

2024-07-13 04:31 UTC, AnisanYT approved these changes
Hola, excelente, no veo ningún error, por mi parte, puedes continuar.

2024-07-15 12:17 UTC, ebarahonautn requested changes

2024-07-15 12:17 UTC, ebarahonautn commented on models/lab/model.py
@JOSEEAND por favor hacer nuevamente pull de dev, porque este archivo models/lab/model.py se le hizo revert de unos cambios y actualmente tiene la funcionalidad original.

2024-07-15 12:17 UTC, ebarahonautn commented on service.py
@JOSEEAND hacer pull de dev porque este archivo tiene otros cambios en ese branch.

2024-07-15 12:17 UTC, ebarahonautn commented on swagger.yml
@JOSEEAND por favor actualizar el swagger con el correcto response, ya que se debe devolver la misma estructura de la tabla

![Screenshot 2024-07-15 at 6 12 07 AM](https://github.com/user-attachments/assets/b41c6884-c36e-4837-95e3-c99be237d25f)
![Screenshot 2024-07-15 at 6 12 24 AM](https://github.com/user-attachments/assets/5f946769-5dfb-4e0d-8dd7-eb629c52d879)

2024-07-18 17:07 UTC, ebarahonautn approved these changes

2024-07-18 17:07 UTC, merged